# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_company', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=50)),
                ('point_of_contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=100)),
                ('complaint_description', models.CharField(max_length=5000)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Client')),
                ('linked_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(blank=True, max_length=254)),
                ('customer', models.BooleanField(default=True)),
                ('provider', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_company', models.CharField(max_length=50)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_contact', models.CharField(max_length=12)),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('min_duration', models.CharField(max_length=50)),
                ('service_objective', models.CharField(max_length=1000)),
                ('service_description', models.CharField(max_length=5000)),
                ('offering_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Client')),
                ('offering_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company')),
                ('serviceSelected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Service')),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('target_audience', models.CharField(max_length=500)),
                ('service_objective', models.CharField(max_length=5000)),
                ('performance_parameter', models.CharField(max_length=5000)),
                ('performance_measure', models.CharField(max_length=5000)),
                ('service_hours', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Client')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company')),
                ('min_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_min_duration', to='ComplaintsForum.Service')),
                ('point_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_point_of_contact', to='ComplaintsForum.Company')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Service')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_service_name', to='ComplaintsForum.Service')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
