# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintsForum', '0002_chat_client_company_service_sla'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Service')),
            ],
        ),
    ]
