# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintsForum', '0003_serviceprovided'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_company', models.CharField(max_length=50)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceprovided',
            name='offering_company',
        ),
        migrations.RemoveField(
            model_name='serviceprovided',
            name='service_name',
        ),
        migrations.DeleteModel(
            name='ServiceProvided',
        ),
    ]
