# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintsForum', '0004_auto_20170711_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='last_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='client_name',
            field=models.ForeignKey(default='abc', on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='ABC', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='linked_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company'),
        ),
        migrations.AlterField(
            model_name='sla',
            name='point_of_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_point_of_contact', to='ComplaintsForum.Company'),
        ),
        migrations.AddField(
            model_name='serviceselected',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Client'),
        ),
        migrations.AddField(
            model_name='serviceselected',
            name='offering_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Company'),
        ),
        migrations.AddField(
            model_name='serviceselected',
            name='serviceSelected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComplaintsForum.Service'),
        ),
    ]
