# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintsForum', '0005_auto_20170713_0829'),
        ('ComplaintsForum', '0005_auto_20170713_1359'),
    ]

    operations = [
    ]
